google-cloud-sdk update to 277.0.0-2

diff --git a/personal/google-cloud-sdk/PKGBUILD b/personal/google-cloud-sdk/PKGBUILD
--- a/personal/google-cloud-sdk/PKGBUILD
+++ b/personal/google-cloud-sdk/PKGBUILD
@@ -6,31 +6,41 @@
 # Contributor: Justin Dray <justin@dray.be>
 
 pkgname="google-cloud-sdk"
-pkgver=276.0.0
-pkgrel=1
+pkgver=277.0.0
+pkgrel=2
 pkgdesc="A set of command-line tools for the Google Cloud Platform. Includes gcloud (with beta and alpha commands), gsutil, and bq."
 url="https://cloud.google.com/sdk/"
 license=("Apache")
 arch=('x86_64')
 depends=('python' 'python2')
 optdepends=(
-  "python: [cli] beta support for python3. see https://cloud.google.com/sdk/gcloud/reference/topic/startup"
-  "python2-crcmod: [gsutil] verify the integrity of GCS object contents"
+  "python-crcmod: [gsutil] verify the integrity of GCS object contents"
 )
 options=('!strip' 'staticlibs')
 source=(
   "https://dl.google.com/dl/cloudsdk/release/downloads/for_packagers/linux/${pkgname}_${pkgver}.orig.tar.gz"
   "google-cloud-sdk.sh"
+  "0001-fix-console-io-syntax-warning.patch"
+  "0002-set-python2-for-dev-appserver-py.patch"
+  "0003-set-python2-for-endpointscfg-py.patch"
 )
-sha256sums=('ad3d711e372fdcef141106d33e150aee4922a88c76484798a40b48a2fc779c3c'
-            '36ac88de630e49ea4b067b1f5f229142e4cf97561b98b3bd3d8115a356946692')
+sha256sums=('d7b8ee536eddc728aedc5dec867766f51a594d7ba024f5f8ba547088945d76e9'
+            'a54f88947a2593fae4aa8f65e42de4ad735583ae743735305c0f36710a794295'
+            'b3faeb3af2922510048d12063fa215610f12879f5cc9f8b78786c7d9f2957c70'
+            '62ec7f56e09168d375823e9e99fcdcfbf40b0fffdd75f35cf91122c5902c82e9'
+            'ff6065ce2e54ac654605bd5fe554313b1d0def2c31ce56ff39429098dd1e39fe')
+
+prepare() {
+  cd "$pkgname"
+
+  for f in ./../*.patch; do
+    patch -p1 -i $f > /dev/null 2>&1 || ( echo "failed to apply patch: $(basename $f)" && exit 1 )
+  done
+}
 
 package() {
-  echo "Copying core SDK components"
   mkdir "${pkgdir}/opt"
   cp -r "${srcdir}/${pkgname}" "${pkgdir}/opt"
-
-  echo "Running bootstrapping script"
 
   # The Google code uses a _TraceAction() method which spams the screen even
   # in "quiet" mode, we're throwing away output on purpose to keep it clean
@@ -43,32 +53,27 @@ package() {
     --additional-components "" \
     1 > /dev/null
 
-  echo "Cleaning up artifacts of the bootstrap script"
   rm -rf "${pkgdir}/opt/${pkgname}/.install/.backup"
   mkdir "${pkgdir}/opt/${pkgname}/.install/.backup"
+  find $pkgdir -name '__pycache__' -type d -exec rm -rf {} +
 
-  echo "Setting up profile environment variables"
   install -Dm755 "${srcdir}/${source[1]}" \
     "${pkgdir}/etc/profile.d/google-cloud-sdk.sh"
 
-  echo "Installing bash completion script"
   install -Dm755 "${pkgdir}/opt/${pkgname}/completion.bash.inc" \
     "${pkgdir}/etc/bash_completion.d/google-cloud-sdk"
 
-  echo "Installing man pages"
   mkdir -p "${pkgdir}/usr/share"
   mv -f "${pkgdir}/opt/${pkgname}/help/man" "${pkgdir}/usr/share/"
   chmod 0755 "${pkgdir}/usr/share/man"
   chmod 0755 "${pkgdir}/usr/share/man/man1"
 
-  echo "Creating symlinks for applications"
   mkdir -p "${pkgdir}/usr/bin"
   for i in "${pkgdir}/opt/${pkgname}/bin"/*; do
     ln -st "${pkgdir}/usr/bin/" "${i#${pkgdir}}"
   done
   rm -f "${pkgdir}"/usr/bin/{bq,dev_appserver.py*,endpointscfg.py*,java_dev_appserver.sh}
 
-  echo "Fixing file permissions"
   chmod -x "${pkgdir}"/usr/share/man/man1/*
   find "${pkgdir}/opt/${pkgname}" -name "*.html" -o -name "*.json" -exec chmod -x {} \;
   find "${pkgdir}/opt/${pkgname}" -name "*_test.py" -exec chmod +x {} \;
