google-cloud-sdk update to 286.0.0-1

diff --git a/personal/google-cloud-sdk/PKGBUILD b/personal/google-cloud-sdk/PKGBUILD
--- a/personal/google-cloud-sdk/PKGBUILD
+++ b/personal/google-cloud-sdk/PKGBUILD
@@ -6,8 +6,8 @@
 # Contributor: Justin Dray <justin@dray.be>
 
 pkgname="google-cloud-sdk"
-pkgver=285.0.1
-pkgrel=2
+pkgver=286.0.0
+pkgrel=1
 pkgdesc="A set of command-line tools for the Google Cloud Platform. Includes gcloud (with beta and alpha commands), gsutil, and bq."
 url="https://cloud.google.com/sdk/"
 license=("Apache")
@@ -25,17 +25,24 @@ source=(
   "0002-set-python2-for-dev-appserver-py.patch"
   "0003-set-python2-for-endpointscfg-py.patch"
 )
-sha256sums=('39d9424c5f90e3d27fedbf3bf1a6040dc0ad3ce773f5d2881ff6e9a676d17730'
+sha256sums=('24f1be5a0065efa4e5bfa33b6184ab71b5a55ffd72d27f2fa152a472715aa671'
             'a54f88947a2593fae4aa8f65e42de4ad735583ae743735305c0f36710a794295'
             'b3faeb3af2922510048d12063fa215610f12879f5cc9f8b78786c7d9f2957c70'
             '62ec7f56e09168d375823e9e99fcdcfbf40b0fffdd75f35cf91122c5902c82e9'
             'ff6065ce2e54ac654605bd5fe554313b1d0def2c31ce56ff39429098dd1e39fe')
 
 prepare() {
-  cd "$pkgname"
+  cd "${srcdir}/${pkgname}"
 
-  for f in ./../*.patch; do
-    patch -p1 -i $f > /dev/null 2>&1 || ( echo "failed to apply patch: $(basename $f)" && exit 1 )
+  for f in "${source[@]}"; do
+    [[ "$f" =~ \.patch$ ]] && \
+    ( \
+      patch -p1 -i "${srcdir}/${f}" > /dev/null 2>&1 ||\
+      ( \
+        echo "failed to apply patch: $(basename ${f})" && \
+        exit 1 \
+      ) \
+    )
   done
 }
 
